### ISSUE TITLE
SQLCiphe r.bundle" not found. Run 'pod install' to update the copy resources script.

### ISSUE THREAD

**Issue by suprimpoudel** [davidmartos96/sqflite_sqlcipher#104]
**pubspec.yaml**
```
name: project
description: Project

publish_to: "none"

version: 3.0.0+3

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_zoom_drawer: ^3.2.0
  provider: ^6.1.2
  flutter_staggered_grid_view: ^0.4.1
  focused_menu: ^1.0.5
  toggle_switch: ^2.3.0
  settings_ui: ^2.0.2
  file_picker: ^8.3.7
  fluttertoast: ^8.2.10
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  firebase_analytics: ^11.3.6
  firebase_crashlytics: ^4.2.0
  flutter_facebook_auth: ^7.1.1
  intl: ^0.19.0
  expandable_text: ^2.3.0
  shared_preferences: ^2.3.4
  flutter_easyloading: ^3.0.5
  pinput: ^1.2.2
  cloud_firestore: ^5.6.0
  universal_platform: ^1.1.0
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  file_manager: ^1.0.2
  encrypt: ^5.0.3
  signature: ^5.5.0
  flutter_inappwebview: ^6.1.5
  get: ^4.6.6
  flutter_signature_pad: ^3.0.1
  sign_in_with_apple: ^6.1.4
  intl_phone_field: ^3.2.0
  pinch_zoom: ^1.0.0
  local_auth: ^2.3.0
  multi_select_flutter: ^4.1.3
  logging: ^1.3.0
  flutter_slidable: ^4.0.0
  open_file: ^3.5.10
  internet_connection_checker: ^3.0.1
  dio: ^5.7.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  crypto: ^3.0.6
  flutter_widget_from_html_core: ^0.15.2
  url_launcher: ^6.3.1
  dropdown_search: ^5.0.6
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  flutter_background: ^1.3.0+1
  share_plus: ^10.1.4
  mobile_scanner: ^6.0.10
  google_mobile_ads: ^5.3.1
  flutter_svg: ^2.0.17
  carousel_slider:
    git:
      url: https://github.com/sampaio96/flutter_carousel_slider.git
      ref: master
  flutter_localizations:
    sdk: flutter
  device_info_plus: ^11.3.0
  flutter_secure_storage: ^9.2.4
  sqflite_sqlcipher: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
  flutter_launcher_icons: ^0.14.2
  firebase_core_platform_interface: ^5.4.0


flutter_icons:
  image_path: 'assets/images/app_icon.png'
  android: true
  ios: true
 
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - lib/l10n/

  fonts:
    - family: Helvetica-Bold
      fonts:
        - asset: assets/fonts/Helvetica-Bold.ttf
    - family: Helvetica-BoldOblique
      fonts:
        - asset: assets/fonts/Helvetica-BoldOblique.ttf
    - family: Helvetica-Oblique
      fonts:
        - asset: assets/fonts/Helvetica-Oblique.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
    - family: trend-sans-four
      fonts:
        - asset: assets/fonts/trend-sans-four.ttf
    - family: Myriad-Pro-Regular
      fonts:
        - asset: assets/fonts/Myriad-Pro-Regular.ttf
```

**Flutter doctor log**
```
flutter doctor --verbose
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.5 24F74 darwin-arm64 (Rosetta),
    locale en-NP)
    • Flutter version 3.27.0 on channel stable at
      /Users/***/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (6 months ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/***/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.100.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • *** iPhone (mobile)        • *** • ios            • iOS 18.5 ***
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.5 24F74 darwin-arm64 (Rosetta)
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.5 24F74 darwin-arm64 (Rosetta)
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome ***
    ! Error: Browsing on the local area network for ***’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.
```

I'm facing an issue archiving my Flutter iOS project because it uses both the sqflite and sqflite_sqlcipher packages, which appears to cause a conflict.

Previously, I encountered the error:

> Multiple commands produce '/Users/username/Library/Developer/Xcode/DerivedData/Runner-fcxhffjmdtbzsbcfbguxqatlgxnj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SQLCipher.bundle'

I resolved that using a workaround from this GitHub issue. https://github.com/davidmartos96/sqflite_sqlcipher/issues/95

However, after resolving several related issues, I'm now stuck with the following error during the archive process:

> error: Resource "/Users/***/Library/Developer/Xcode/DerivedData/Runner-gijkukldmiazimdfhmkakrktobrt/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/FMDB/SQLCipher.bundle" not found. Run 'pod install' to update the copy resources script.
I’ve already tried running pod install and pod update, cleaning the project (flutter clean), and rebuilding, but the issue persists.

Has anyone encountered and solved this kind of problem when using both sqflite and sqflite_sqlcipher together in a Flutter project?

I’ve attached my pubspec.yaml and output of flutter doctor --verbose for reference.

Thanks in advance!
