### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by AndreaMiotto** [davidmartos96/sqflite_sqlcipher#2]
Hi, it's not clear to me how to install the package and how to use it.
Any tips?

Thanks

**Comment by davidmartos96** [comment]
Yes, you are right. I should add some instructions on the README.

This is what you need to add to the pubspec.yml:

```
sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: 889a156
```
The ref tag is just to point to one specific commit. Safer than using master directly, although I don't intend  to make any commits because the fork has been working great for my use case.
