### ISSUE TITLE
depends on dependency_overrides from unknown source "sqflite", version solving failed

### ISSUE THREAD

**Issue by hqzxbb** [davidmartos96/sqflite_sqlcipher#34]
hi, i use this code in my pubspec.yaml

`dependency_overrides:
  sqflite:
      git:
        url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
        path: sqflite
        ref: fmdb_override`

when i run flutter pub get, get this:
`Running "flutter pub get" in app-base...                  
Because app_base depends on dependency_overrides from unknown source "sqflite", version solving failed.
pub get failed (1; Because app_base depends on dependency_overrides from unknown source "sqflite", version solving failed.)
exit code 1`
please help me

**Comment by davidmartos96** [comment]
@hqzxbb    That is only needed when you use other packages that  depend on `sqflite`. For example `cached_network_image`. Could you post your pubspec.yaml here?
You can use triple back ticks at the start and at the end to paste a multiline text.

**Comment by hqzxbb** [comment]
this is my pubspec.ymal,
```
name: app_base
description: A new flutter package project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
    # local lib
  flutter_localizations:
    sdk: flutter

  dio: 3.0.10
  image_picker: 0.6.7+11
  fluttertoast: 3.1.3
  shared_preferences: 0.5.12
  event_bus: 1.1.1
  cached_network_image: 2.3.3
  pull_to_refresh: 1.6.2
  sqflite: 1.3.1+1
  fluro: 1.7.8
  dependency_overrides:
    sqflite:
      git:
        url: http://alm.adc.com/oppo_enterprise_it/TeamTalk/_git/flutter_package_sqlcipher
        path: sqflite
        ref: fmdb_override
ev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/common/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
```
