### ISSUE TITLE
Problem when using cached_network_image

### ISSUE THREAD

**Issue by andrewpmoore** [davidmartos96/sqflite_sqlcipher#4]
I was planning on trying to use your version of sqlite for encryption but it seems to cause issues with using cached_network_image which also uses sqflite which means I get the following error:

_**Because no versions of cached_network_image match >1.1.1 <2.0.0 and cached_network_image 1.1.1 depends on flutter_cache_manager ^1.1.1, cached_network_image ^1.1.1 requires flutter_cache_manager ^1.1.1.**_

_**Because flutter_cache_manager 1.1.1 depends on sqflite ^1.1.0 and no versions of flutter_cache_manager match >1.1.1 <2.0.0, flutter_cache_manager ^1.1.1 requires sqflite ^1.1.0.**_

_**Thus, cached_network_image ^1.1.1 requires sqflite from hosted.
So, because fmps depends on both cached_network_image ^1.1.1 and sqflite from git, version solving failed.**_

Can you think what's a simple way around this?

**Comment by davidmartos96** [comment]
Yes, I have also came around this in one of my apps. The issue is that one of the dependencies (cache_manager) is using a different sqlite version to the one in your app.
You can use the `dependency_overrides` option in your pubspec.

```
dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: 0eff382dcc45322edfa94d222cadf3e28fc5a95a
```

That is the workaround I am currently using.
